# This is a basic workflow to help you get started with Actions 
# should be triggered in every merge request
# Check if default branch is main/master
# Check if merge is to default branch
# Check if there is no develop branch 

name: TBD compliance check1
# Triggers the workflow on each pull request events regardless of the branch.
on: [pull_request]

jobs:
  TBD-compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: fail if default branch is not main or master
        if: ${{!(github.event.repository.default_branch == 'main' || github.event.repository.default_branch == 'master')}}
        run: exit 1
               
      - name: fail if base branch of the pull request is not the default branch
        if: github.event.repository.default_branch != github.base_ref
        run: exit 1
        
      - name: get branches (Internal preparation step)          
        uses: octokit/request-action@v2.x
        id: get_branches
        with:
          route: GET /repos/{owner}/branches
          owner: ${{github.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: process the list of branches (Internal preparation step)
        id: process_branches_id
        env:
          BRNACHES: ${{ steps.get_branches.outputs.data}}
        run: |
          res=$(echo "$BRNACHES" | jq '.[] | {branch: .name}' | tr -d '\n' )
          echo "::set-output name=branches::$res" 
      
      - name: fail if develop branch exist
        if: contains(steps.get_branches.outputs.data, 'develop')
        run: exit 1
