# This is a basic workflow to help you get started with Actions 
# should be triggered in every merge request
# Check if default branch is main/master
# Check if merge is to default branch
# Check if there is no develop branch 

name: MERGE FLOW CHECK
# Triggers the workflow on each pull request events regardless of the branch.
on: [pull_request, workflow_dispatch]

jobs:
  MERGE-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: process the list of branches (Internal preparation step)
        id: process_branch_ids
        env:
          BRANCHES: ${{github.event_name}}
        run: |
          echo "::set-output name=branch::GGGG_${BRANCHES^^}" 
      - name: fail always
        id: fail_always
        run: |
          exit 1
  OTHERS:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged != true }}
    steps:
      - name: process the list of branches (Internal preparation step)
        id: process_branch_ids
        env:
          BRANCHES: ${{github.event_name}}
        run: |
          echo "${BRANCHES^^}" 
