name: Auto-release for accepted tickets
concurrency:
  group: auto_deploy_release_action
  cancel-in-progress: false
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: install npm packages
        run: |
          npm i axios
          npm i nodemailer

      - name: auto merge ready (deployed) tickets
        id: auto-merge
        uses: actions/github-script@v4
        with:
          result-encoding: json
          script: |
            const axios = require("axios");
            const nodemailer = require("nodemailer");
            const jiraKeyRegex = new RegExp('LAMBDA-[0-9]+', 'gim');
            const prNumberRegex = new RegExp('(.+pull\/)(\d+)(.*)', 'gim');
            const {owner, repo} = context.repo;
            let pullsCandidateForDeployment = [];
            
            
            const pulls = (await github.pulls.list({ owner, repo, state: "open", base: "main" })).data;
            console.info(`Open PRs: ${pulls.map(p => p.number)}`);
            for (const pull of pulls) {
            
         
            
             for await (const response of github.paginate.iterator(
              github.pulls.listFiles,
              {
                owner: owner,
                repo: repo, 
                pull_number: pull.number
              }
            )) {

               console.info(`PR #${pull.number}: ${response}`);
              // do whatever you want with each response, break out of the loop, etc.

            }           
            
            
            
            
            
            
            
              const matches = pull.title.match(jiraKeyRegex);
              if (!matches) {
                console.info(`PR #${pull.number}: title does not contain a ticket key. SKIP.`);
                continue;
              }
              let candidate = {
               "pull": pull,
               "labels": [],
               "issueKey": 'LAMBDA-1414',
               "valid" : 1
               }
               pullsCandidateForDeployment.push(candidate);

             }
             let candidate = null;
            //in case candidate == null (no PR without "pending-deployment) but pullsCandidateForDeployment is not empty, choose random pull request
            //This is the case where we all pending PR failed deployment at their 1st attempt. we don't want to keep trying the same one.             
            if (pullsCandidateForDeployment.length > 0) {
                const idx = Math.floor(Math.random() * pullsCandidateForDeployment.length);
                candidate = pullsCandidateForDeployment[idx];
            }
            if (candidate != null ) {
              return pullsCandidateForDeployment[0]
            } else {
              return {"valid": 0};
            }   
        
      - name: 'echo'
        id: aaa
        env:
          PULL: ${{steps.auto-merge.outputs.result}}
        run: |
          echo "$PULL"
          val=$(echo "$PULL"  |  jq '.valid // empty' )
          res=$(echo "$PULL"  |  jq '.pull.title // empty' )
          res1=$(echo "$PULL" |  jq '.pull.html_url // empty'  )
          res2=$(echo "$PULL" |  jq '.issueKey // empty')
          
          echo "::set-output name=title::$res" 
          echo "::set-output name=html::$res1" 
          echo "::set-output name=issue::$res2"
          echo "::set-output name=valid ::$val"
      - name: 'print deployment candidate PR title'
        if:  steps.aaa.outputs.valid == 1
        run: echo "${{steps.aaa.outputs.title}}"
      - name: 'print deployment candidate PR HTML'
        if:  steps.aaa.outputs.valid == 1
        run: echo "${{steps.aaa.outputs.html}}"
      - name: 'print deployment candidate PR issue'
        if:  steps.aaa.outputs.valid == 1
        run: echo "${{steps.aaa.outputs.issue}}"
