# This is a basic workflow to help you get started with Actions 
# should be triggered in every merge request
# Check if default branch is main/master
# Check if merge is to default branch
# Check if there is no develop branch 

name: TEST expressions
# Triggers the workflow on each pull request events regardless of the branch.
on: [workflow_dispatch, pull_request]
jobs:
  manual-qa-check:
   - name: print labels
        run: |
         echo "${{github.event.pull_request.labels.*.name}}"

   - name: print expression value
        run: |
         echo "${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'skip-backend-deployment') }}"

   - name: print expression value2
        run: |
         echo "${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip-backend-deployment') }}"
                 
    - name: print expression value3
        run: |
          if [ ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'skip-backend-deployment') }}]; then
            skipBackend="true"
            echo "skipping backend"
          fi 
          if [ ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip-backend-deployment') }}]; then
            skipBackend="false"
            echo "skipping backend FALSE"
          fi

          
              